@startuml tentativo2

skinparam monochrome true
hide circle
skinparam classAttributeIconSize 0

Abstract Pregunta {
    - categoria: str
    - opciones: Opciones []
    - pregunta: str
    + obtenerOpciones(): Opciones[]
    + validarOpciones(Opcion[]): Puntaje
    + validarOpciones(Opcion): Puntaje
}

class Turno {
    - anulador: Anulador
    - exclusividad: Exclusividad
}

class GestorPreguntas {
    - preguntas: Pregunta[]
}

class Jugador {


}

class Respuesta {
    - puntaje: int
    - multiplicador: Multiplicador
}

Jugador <- GestorDeTurnos
GestorDeTurnos -down-> GestorPreguntas
GestorDeTurnos -down-> "*" Turno
GestorPreguntas *-->"*" Pregunta
Turno --> Pregunta
Turno .> GestorPreguntas
Turno --> "*" Respuesta
Respuesta --> Jugador

@enduml