@startuml tentativo2

skinparam monochrome true
hide circle
skinparam classAttributeIconSize 0

Abstract Pregunta {
    - categoria: str
    - opciones: Opciones []
    - pregunta: str
    + validarSeleccion(jugada: Jugada): Respuesta
}

class Turno {
    - anulador: Anulador
    - exclusividad: Exclusividad
    + jugarTurno(lista: Jugador[])
}

class GestorPreguntas {
    - preguntas: Pregunta[]
}

class Jugador {
    - nombre: str
    - puntajeTotal: Puntaje
    + obtenerJugada(): Jugada

}

class Respuesta {
    - puntaje: int
    - modificadores: Modificador[]
    + Respuesta(p: Puntaje, m: Modificador, j: Jugador)
    + actualizarPuntajeDelJugador()
}

class AlgoHoot {

}

Jugador <- GestorDeTurnos
GestorDeTurnos -down-> GestorPreguntas
GestorDeTurnos -down-> "*" Turno
GestorPreguntas *-->"*" Pregunta
Turno --> Pregunta
Turno .> GestorPreguntas
Turno --> "*" Respuesta
Respuesta --> Jugador

@enduml