@startuml Clases
skinparam classAttributeIconSize 0
interface Joker {
{abstract}+aplicarModificador(Carta, Puntaje, Juego): Puntaje
}

interface JokerPuntaje {
{abstract}+aplicarModificador(Carta, Puntaje, Juego): Puntaje
}

interface JokerDescarte {
{abstract}+aplicarModificador(Carta, Puntaje, Juego): Puntaje
}

interface JokerJuego {
{abstract}+aplicarModificador(Carta, Puntaje, Juego): Puntaje
}

interface JokerAleatorio{
{abstract}+aplicarModificador(Carta, Puntaje, Juego): Puntaje
}

interface JokerCombinacion{
{abstract}+aplicarModificador(Carta, Puntaje, Juego): Puntaje
}

Joker <|.up. JokerPuntaje
Joker <|.up. JokerDescarte
Joker <|.. JokerJuego
Joker <|.. JokerAleatorio
Joker <|.right. JokerCombinacion

@enduml Clases