@startuml Preguntas

skinparam monochrome true
hide circle
skinparam classAttributeIconSize 0

abstract Pregunta <<Abstract>> {
    - pregunta: String
    - tematica: String
    - opciones: List<Opcion>
    + mostrarPanel()
    + validarSeleccion(s: Seleccion): Puntaje
}

class VerdaderoFalso {
    - opcionCorrecta: Opcion
    + mostrarPanel()
    + validarSeleccion(s: Seleccion): Puntaje

}

class MultipleChoice {
    + mostrarPanel()
    + validarSeleccion(s: Seleccion): Puntaje

}

class OrderedChoice {
    - ordenCorrecto
    + mostrarPanel()
    + validarSeleccion(s: Seleccion): Puntaje

}

class GroupChoice {
    - separacionCorrecta
    + mostrarPanel()
    + validarSeleccion(s: Seleccion): Puntaje

}

Pregunta <|-down- VerdaderoFalso
Pregunta <|-down- MultipleChoice
Pregunta <|-left- OrderedChoice
Pregunta <|-right- GroupChoice

interface TipoVF <<Interface>> {
    + devolverPuntaje(Boolean acierta): Puntaje
}

VerdaderoFalso -left-> TipoVF

abstract TipoMC <<Abstract>> {
    - opcionesCorrectas
    + TipoMC(opcionesCorrectas)
    + validarSeleccion(s: Seleccion): Puntaje
}

MultipleChoice -right-> TipoMC
@enduml