@startuml unTurno
skinparam monochrome true
hide footbox
skinparam classAttributeIconSize 0


participant "Vista" as gui
actor ":Control" as g
participant ":Turno" as t
participant "j:Jugador" as j
participant "p:PreguntaVF" as p
participant "r:Respuesta" as r
participant ":Exclusividad" as e
participant ":Anulador" as an

activate gui

gui -> g: iniciarJuego()
g -> t: obtenerPregunta()
g <-- t: unaPregunta
g -> t: obtenerOpciones()
g <-- t: unasOpciones
gui <- g: mostrarPregunta(unaPregunta)
gui <- g: mostrarOpcion(unaOpcion)

g -> t: responder(j,jugada)
activate t

    t -> p: validarOpcion(seleccion)
    activate p

        t <-- p: puntaje
    deactivate p
    create r
    t -> r: Respuesta(puntaje,modificador,jugador)
    t -> t: registrarRespuesta(r)


t -> e: aplicarExclusividad(listaRespuestas)

t -> an: aplicarAnulador()

loop para cada respuesta registrada
    t -> r: actualizarPuntajeDelJugador()
end

deactivate t
@enduml