@startuml clasesGenerales

skinparam monochrome false
/'skinparam monochrome true'/
/'hide circle '/
skinparam classAttributeIconSize 0

interface Pregunta {
    + getPregunta(): String
    + getOpciones(): List<Opcion>
    + responder(respuestas:List<Respuesta>): PuntajeParcial
    + getTematica(): String
    + getTextoRespuesta(): String
}

class GestorDeTurnos {
    +comenzarNuevaRonda():void
    +obtenerPreguntaRondaActual(): Pregunta
    +jugarRondaActual(j:Jugador ,modsInd:List<ModificadorIndividual> ,modsGlob:List<ModificadorGlobal> ,respuestas:List<Respuesta>): void
    +terminarRondaActual(): void
    +agregarJugador(Jugador): void
    +obtenerJugadores(): List<Jugador>
}

class RondaDePreguntas {
    - puntajes:List<PuntajeParcial>
    + RondaDePreguntas(pregunta:Pregunta)
    + jugar(j:Jugador,modsInd:List<ModificadorIndividual> ,modsGlob:List<ModificadorGlobal>,respuestas: List<Respuesta>): void
    + terminar(): void
}

class OrdenDeRonda {
    - turno: int
    + OrdenDeRonda(List<Jugador>)
    + obtenerJugadorActual():Jugador
    + obtenerTurno():int
    + avanzarTurno():void
    + rondaFinalizada():bool

}

class GestorPreguntas {
    +GestorPreguntas(preguntas:List<Pregunta>)
    +obtenerSiguientePregunta(): Pregunta
}

class Jugador {
    - nombre: str
    - puntosTotales: PuntajeTotal
    + Jugador(nombre:String):void
    + gastar(mod:ModificadorIndividual):void
    + obtenerPuntaje(): int
    + sumarPuntos(puntaje:int):void
    + equals(jugador:Jugador): bool
}

class Respuesta {
    - respuesta:String
    + Respuesta(respuesta:String)
    + equals(opcion:String) : bool
}

class AlgoHoot {
    - instancia: AlgoHoot
    + {static}getInstancia(): AlgoHoot
    + comenzarNuevaRondaDePreguntas(): void
    + jugarRondaDePreguntas(j:Jugador ,modsInd:List<ModificadorIndividual> ,modsGlob:List<ModificadorGlobal> ,respuestas:List<Respuesta>): void
    + terminarRondaDePreguntas(): void
    + obtenerPreguntaActual(): Pregunta
    + agregarJugador(jugador:Jugador):void
    + obtenerJugadores(): List<Jugador>
}

class Lector{
    +cargarPreguntas(): List<Pregunta>
}

interface ModificadorIndividual{
    + {abstract} modificar(unPuntaje:int): int
}

interface ModificadorGlobal{
    +aplicar(puntajes:List<PuntajeParcial>): void
}

class PuntajeParcial{
    -puntajeBase:int
    +PuntajeParcial()
    +PuntajeParcial(puntajeInicial:int)
    +sumar(otroPuntaje:PuntajeParcial):void
    +establecerJugador(jugador:Jugador):void
    +agregarModificador(mod:ModificadorIndividual):void
    +obtenerPuntos():int
    +equals(puntaje:Object):
    +perteneceA(j:Jugador):bool
    +actualizarPuntajeDelJugador():void
}


GestorDeTurnos -down-> GestorPreguntas
GestorDeTurnos -down-> "*" RondaDePreguntas
GestorPreguntas o-->"*" Pregunta
GestorPreguntas ..> Lector
RondaDePreguntas --> Pregunta
RondaDePreguntas --> "*" Respuesta
RondaDePreguntas --> OrdenDeRonda
OrdenDeRonda --> "*" Jugador
AlgoHoot --> GestorDeTurnos
GestorDeTurnos -left->"*" Jugador
PuntajeParcial --> Jugador
Respuesta ..> PuntajeParcial

Jugador --> "2" ModificadorIndividual
RondaDePreguntas -->"*" ModificadorGlobal


@enduml
