@startuml

skin rose

actor Jugador
Jugador -> ":CartasSeleccionadas" as CartasSeleccionadas :tirarMano(Jokers)
CartasSeleccionadas -> ":Juego" as Juego :puntuarMano()
CartasSeleccionadas <-- Juego :Puntaje del juego
loop para toda carta
CartasSeleccionadas -> ":Carta" as Carta :obtenerPunto()
Carta -> ":Estado" as Estado :aplicarModificador(Puntaje)
Carta  <-- Estado :Puntaje del estado
CartasSeleccionadas <-- Carta :Puntaje de la carta
loop para todos los jokers (de izq a der)
CartasSeleccionadas -> ":Joker" as Joker :aplicarModificador(Carta, puntajeActual, Juego)
CartasSeleccionadas <-- Joker :Puntaje del joker a partir de una carta o juego
end
end
Jugador <-- CartasSeleccionadas : Puntaje total

@enduml