@startuml

skin rose

actor Jugador
Jugador -> "cartasSeleccionadas: ManoDe5" as CartasSeleccionadas : jugarMano()
CartasSeleccionadas -> ":Juego" as Juego :puntuarMano(List <Carta> cartas)
Juego -> ":Tarot" as Tarot: obtenerPuntaje(Puntaje puntajeDelJuego)
Juego <-- Tarot: Puntaje puntajeModificadoPorTarot
loop para toda carta
Juego -> ":Carta" as Carta :obtenerPuntaje()
Carta -> ":Tarot" as TarotDeLaCarta :obtenerPuntaje(Puntaje puntajeDeLaCarta)
Carta  <-- TarotDeLaCarta :Puntaje del estado
Juego <-- Carta :Puntaje de la carta
Juego -> Puntaje: sumar(Puntaje puntajeObtenido)
Juego <-- Puntaje : Puntaje Parcial
end

CartasSeleccionadas <-- Juego : Puntaje puntajeTotal
CartasSeleccionadas -> Puntaje : calcularValor(Puntaje puntajeTotal)
CartasSeleccionadas <-- Puntaje : Int puntajeTotal
Jugador <-- CartasSeleccionadas : Int puntajeTotal
@enduml