@startuml DiagramaGroupChoice

skinparam monochrome true
hide circle
skinparam classAttributeIconSize 0

class Pregunta {
    + responder(e: Eleccion)
}

abstract Solucion <<Abstract>> {
    + puntuar(e: Eleccion): Puntaje
}

class SolucionCorrecta extends Solucion {
    + puntuar(e: Eleccion): Puntaje
}

class SolucionIncorrecta extends Solucion {
    + puntuar(e: Eleccion): Puntaje
}

class Opcion {
    - opcion: String
    + equals(e: Eleccion): bool
}


Solucion <- Pregunta
Solucion -left-> Eleccion
class Orden {
    - orden: OrderedList<Opcion>
    + equals(e: Eleccion): bool
}

class Grupo {
    - grupo: Set<Opcion>
    + equals(e: Eleccion): bool
}

interface Eleccion <<Interface>> {
    + equals(e: Eleccion): bool
}

Orden .down.|> Eleccion
Grupo .down.|> Eleccion
Opcion .down.|> Eleccion

@enduml