name: Run Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run build script
        run: ./scripts/build.sh